can_serial_node:
  ros__parameters:
    # PID 控制器参数
    Kp: 0.7                   # 比例系数 (默认值 0.01)
    Ki: 0.0                      # 积分系数 (默认值 0.0)
    Kd: 0.0                      # 微分系数 (默认值 0.0)

    # 运动限制与死区
    max_speed: 60.0             # 最大输出速度限制
    deadzone: 1.0                # 误差死区像素宽度